### ISSUE TITLE
Make v1.0.0 features compatible with .NET 5 and 6

### ISSUE THREAD

**Issue by lgcmotta** [Liero/vNext.BlazorComponents.FluentValidation#7]
Hello!

I'm using this package on a .NET 5 WebAssembly Blazor application, which is currently using version 0.5.0. We wanted to update the package to be able to use the new features added in version 1.0.0 but it has a compatibility problem with .NET 5 because it depends on the `Microsoft.AspNetCore.Components.Web` package version 6.0.0. I would like to propose a change on the `csproj` file to make this project compatible with .NET 5 and 6 at the same time.

1. Changing the tag `<TargetFramework>` to `<TargetFrameworks>` and add the `net5.0` on the list as follows:

```csproj
  <PropertyGroup>
    <TargetFrameworks>net6.0;net5.0</TargetFrameworks>
    ...
  </PropertyGroup>
```

2. Remove the `<PackageReference>` tag for `Microsoft.AspNetCore.Components.Web` version `6.0.0`.
3. Add two `<ItemGroup>` tags with the following conditions:
```csproj
  <ItemGroup Condition="'$(TargetFramework)' == 'net6.0'">
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net5.0'">
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="5.0.17" />
  </ItemGroup>
```

The package will compile for both target frameworks and will be available on NuGet like this:

![image](https://user-images.githubusercontent.com/33238105/172732975-245b5a20-89d2-4b82-a9ee-1b9c0d0199d7.png)

I'll be glad to open a PR to make these changes if desired!

**Comment by Liero** [comment]
.NET 5 support ended on May 10, 2022. I strongly recommend you to upgrade to .NET 6 which is Long Term Support release.

I've done it myself on couple of project and it is ok even on larger projects.

**Comment by lgcmotta** [comment]
Yes, I'm aware, I have proposed this to my team and we're working on that. Not sure how long will it take to get this approved., but I'll close this issue! Thanks
