### ISSUE TITLE
[Question] : Can i use !editContext.Validate() in an EditForm

### ISSUE THREAD

**Issue by chihabhajji** [Liero/vNext.BlazorComponents.FluentValidation#8]
i'm asking before i migrate because i discovered that the current library i use doesnt handle multiple async validation rules and throws concurrency issues

**Comment by chihabhajji** [comment]
migrated and it worked like a charm, thank you for such a well written library

**Comment by Liero** [comment]
Ideally, provide a minimal demo using https://blazorrepl.telerik.com/?_ga=2.20876792.1502339267.1658216235-759009338.1594450352
