### ISSUE TITLE
Injecting child validators

### ISSUE THREAD

**Issue by chihabhajji** [Liero/vNext.BlazorComponents.FluentValidation#9]
Why is the library unable to inject nested validators and we have to resort to explicitly instantiating them ?

**Comment by Liero** [comment]
Can you be more specific, please?

**Comment by Liero** [comment]
Yeah, that's unfortunately how blazor's EditContext work, so all FluentValidation Blazor integration libraries works like this.

If you call `EditContext.Validate()` (or use EditForm.OnValidSubmit), then child validation rules will be executed using your injected instance, as if you called directly your `MyValidator.Validate()`;

However, when you edit a property on a nested object, Blazor only provides the nested object instance and propertyname (see [FieldChangedEventArgs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.forms.fieldchangedeventargs?view=aspnetcore-6.0) and [FieldIdentifier](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.forms.fieldidentifier?view=aspnetcore-6.0), but I don't know, where the nested object instance come from (I can't map it to parent object property).

For example, if I only get a contact instance in the FieldIdentifier, how do I tell FluentValidation, which rule of CustomerValidator should I validate?

```csharp
public class Customer {
	public Contact PrimaryContact {get; set;} = new Contact { Name = "Contact1" },
	public Contact SecondaryContact {get; set;}  = new Contact { Name = string.Empty },	    
	public Contacts[] Contacts {get; set;}  = Enumerable.Range(1, 5). Select(i => new new Contact { Name = null }).ToArray(),	    
}

public class Contact {
	public string Name {get; set;}
}

class CustomerValidator: AbstractValidator<Customer> {
	public CustomerValidator() {
	        var contactValidator = new new ContactValidator();
	        this.RuleFor(x => PrimaryContact).SetValidator(contactValidator);
	        this.RuleFor(x => SecondaryContact).SetValidator(contactValidator);
		this.RuleForEach(x => x.Contacts).SetValidator(contactValidator);
	}
}
class ContactValidator: AbstractValidator<Contact> {
	public ContactValidator() {
		this.RuleFor(x => x.Name).NotEmpty();
	}
}
```

**Comment by Liero** [comment]
## Use ValidatorFactory

`vNext.BlazorComponents.FluentValidation` gives you complete control on how the nested validators are resolved.

Following example always reuse the same validator instance:

    public class CustomerValidatorFactory
    {
        readonly DefaultValidatorFactory _defaultValidatorFactory;
        readonly ContactValidator _contactValidator;
        readonly CustomerValidator _customerValidator;

        public CustomerValidatorFactory(DefaultValidatorFactory defaultValidatorFactory)
        {
            _contactValidator = new ContactValidator();
            _customerValidator = new CustomerValidator(_contactValidator);
            _defaultValidatorFactory = defaultValidatorFactory;
        }

        public IValidator? CreateValidator(ValidatorFactoryContext context)
            => context.Model switch 
            {
                Contact => _contactValidator,
                Customer => _customerValidator,
                _ => _defaultValidatorFactory.CreateValidator(context)
            };
    }
